DROP TABLE IF EXISTS inspirations;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(50)  NOT NULL,
    email           VARCHAR(100) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    avatar_url      VARCHAR(500),
    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE inspirations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    title           VARCHAR(200) NOT NULL,
    type            VARCHAR(20)  NOT NULL,
    content         TEXT         NOT NULL,
    domain          VARCHAR(200) DEFAULT '',
    tags            VARCHAR(500) DEFAULT '',
    notes           TEXT,
    language        VARCHAR(30),
    source_url      VARCHAR(500),
    image_thumbnail VARCHAR(500),
    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inspirations_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_inspirations_user_created ON inspirations (user_id, created_at);
CREATE INDEX idx_inspirations_type ON inspirations (user_id, type);
CREATE INDEX idx_users_email ON users (email);
